<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>viator_launch</name>
  <version>0.0.0</version>
  <description>Launch files for starting the Viator rover</description>
  <maintainer email="tfrbtcs@uw.edu">trickfire</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>can_moteus</exec_depend>
  <exec_depend>can_rmdx8</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>mission_control_updater</exec_depend>
  <exec_depend>arm</exec_depend>
  <exec_depend>camera</exec_depend>
  <exec_depend>example_node</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>